{% set version = "3.2.7" %}

package:
  name: graphql-core
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/graphql-core/graphql_core-{{ version }}.tar.gz
  sha256: 27b6904bdd3b43f2a0556dad5d579bdfdeab1f38e8e8788e555bdcb586a6f62c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.6.1,<2
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=4,<5

test:
  imports:
    - graphql
  source_files:
    - tests
  requires:
    - pytest >=6.2,<7
    - pytest-asyncio >=0.15,<1
    - pytest-benchmark >=3.4,<4
    - pytest-cov >=2.11,<3
    - pytest-describe >=1,<2
    - pytest-timeout >=1.4,<2
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c '__import__("os").unlink("tests/test_docs.py")'
    - pytest --cov graphql --cov-report term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/graphql-python/graphql-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python 3.6+ port of the GraphQL.js reference implementation of GraphQL.
  doc_url: https://graphql-core-3.readthedocs.io

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
    - KingDarBoja
