{% set name = "graphql-core" %}
{% set version = "2.0.dev20170801051721" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "98460b9dc9ef7996554b9d83651716bfb2e72991c410f2505b699c7ee5389468" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=2.0.dev201708010517210.0
    - promise >=2.0

test:
  imports:
    - graphql
    - graphql.error
    - graphql.execution
    - graphql.execution.executors
    - graphql.execution.experimental
    - graphql.language
    - graphql.pyutils
    - graphql.type
    - graphql.utils
    - graphql.validation
    - graphql.validation.rules

about:
  home: https://github.com/graphql-python/graphql-core
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  license_family: MIT
  summary: 'GraphQL implementation for Python'
  dev_url: https://github.com/graphql-python/graphql-core

extra:
  recipe-maintainers:
    - pmlandwehr
