{% set name = "graphql-core" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da64c472d720da4537a2e8de8ba859210b62841bd47a9be65ca35177f62fe0e4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.10.0
    - promise >=2.1
    - rx >=1.6.0

test:
  imports:
    - graphql

about:
  home: https://github.com/graphql-python/graphql-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'GraphQL base implementation for Python'
  dev_url: https://github.com/graphql-python/graphql-core

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
    - bollwyvl
