# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 3.2.7

package:
  name: graphql-core
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/graphql-core/graphql_core-${{ version }}.tar.gz
  sha256: 27b6904bdd3b43f2a0556dad5d579bdfdeab1f38e8e8788e555bdcb586a6f62c

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.6.1,<3
    - python ${{ python_min }}.*
    - setuptools >=59,<81
  run:
    - python >=${{ python_min }}

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: graphql
  - files:
      source:
        - tests/
    requirements:
      run:
        - pytest >=6.2,<9
        - pytest-asyncio >=0.16,<1
        - pytest-benchmark >=3.4,<6
        - pytest-cov >=4,<7
        - pytest-describe >=2,<3
        - pytest-timeout >=2,<3
        - python ${{ python_min }}.*
    script:
      - python -c '__import__("os").unlink("tests/test_docs.py")'
      - coverage run --source graphql --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=99

about:
  license: MIT
  license_file: LICENSE
  summary: A Python 3.6+ port of the GraphQL.js reference implementation of GraphQL.
  homepage: https://github.com/graphql-python/graphql-core
  documentation: https://graphql-core-3.readthedocs.io

extra:
  recipe-maintainers:
    - carlodri
    - bollwyvl
    - KingDarBoja
